######################################################################
# Automatically generated by qmake (2.01a) Sat Mar 9 09:59:13 2013
######################################################################

TEMPLATE = app
TARGET = bmail
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.hh
SOURCES += main.cpp MainWindow.cpp
