######################################################################
# Automatically generated by qmake (3.0) Sun Jan 26 06:44:44 2014
######################################################################

TEMPLATE = app
TARGET = MyGKrellM
INCLUDEPATH += .

QT += widgets

# Input
HEADERS += cpuinfo.hh \
           IMonitorModule.hpp \
           infocpu.h \
           infomachine.h \
           infomemory.h \
           infonetwork.h \
           Machine.hh \
           Memory.hh \
           Network.hh \
    IMonitorDisplay.hpp
SOURCES += cpuInfo.cpp \
           infocpu.cpp \
           infomachine.cpp \
           infomemory.cpp \
           infonetwork.cpp \
           Machine.cpp \
           main.cpp \
           Memory.cpp \
           Network.cpp \
           search_value.cpp
